[[quizzes]]
id = "exmpquiz"
title = "Example Quiz"
enabled = true
time_limit_minutes = 5
max_attempts = 3
show_score = true
show_corrections = true

    [[quizzes.questions]]
    text = "What color is the sky?"
    type = "radio"
    points = 1
    explanation = "The sky is blue!!!!"
        [[quizzes.questions.answers]]
        text = "Red"
        correct = false
        [[quizzes.questions.answers]]
        text = "Blue"
        correct = true
        [[quizzes.questions.answers]]
        text = "Green"
        correct = false
        [[quizzes.questions.answers]]
        text = "Purple"
        correct = false

    [[quizzes.questions]]
    text = "Whose order is this? "
    type = "text"
    points = 1
    image = "exhibit1.png"
    explanation = "Lolmeow is a big back!"
    regex = "^!?lolme(?:ow|now)$"

    [[quizzes.questions]]
    text = "Match each person to the correct role"
    type = "matching"
    points = 1
    explanation = ""
        [[quizzes.questions.pairs]]
        left = "Anywheres"
        right = "Windows"
        [[quizzes.questions.pairs]]
        left = "eth007"
        right = "Linux"
        [[quizzes.questions.pairs]]
        left = "noobfooditem"
        right = "Cisco"

    [[quizzes.questions]]
    text = "Select everyone that is a mod"
    type = "checkbox"
    points = 1
    explanation = ""
        [[quizzes.questions.answers]]
        text = "x1nni"
        correct = true
        [[quizzes.questions.answers]]
        text = "avril"
        correct = true
        [[quizzes.questions.answers]]
        text = "byrch"
        correct = false
        [[quizzes.questions.answers]]
        text = "lolmeow"
        correct = true


